#cloud-config
users:
  - name: wlanboy
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "" #mkpasswd -m sha-512
    groups: users, sudo, docker
    shell: /bin/bash
    create_groups: true
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 
runcmd:
  # 1. APT configuration and package installation
  - apt-get update
  - apt-get install -y ca-certificates curl
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y nano htop apt-transport-https gnupg2 software-properties-common lsb-release wget net-tools git iptables
  - apt-get install -y docker-ce docker-ce-cli containerd.io

  # 2. Tool installation
  - |
    HELM_VERSION="3.18.2"
    KIND_VERSION="0.29.0"
    ISTIO_VERSION="1.26.2"
    K9S_VERSION="0.50.7"

    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin

    wget "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" -O /tmp/helm.tar.gz
    tar -zxvf /tmp/helm.tar.gz -C /tmp
    mv /tmp/linux-amd64/helm /usr/local/bin/helm
    rm /tmp/helm.tar.gz

    curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64"
    chmod +x ./kind
    mv ./kind /usr/local/bin

    wget "https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux-amd64.tar.gz" -O /tmp/istio.tar.gz
    tar -zxvf /tmp/istio.tar.gz -C /tmp
    mv "/tmp/istio-${ISTIO_VERSION}/bin/istioctl" /usr/local/bin
    rm /tmp/istio.tar.gz

    wget "https://github.com/derailed/k9s/releases/download/v${K9S_VERSION}/k9s_Linux_amd64.tar.gz" -O /tmp/k9s.tar.gz
    tar -zxvf /tmp/k9s.tar.gz -C /tmp
    mv /tmp/k9s /usr/local/bin
    rm /tmp/k9s.tar.gz

  # 3. System configuration
  - sysctl -w net.ipv4.ip_forward=1
  - sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab
  - update-alternatives --set iptables /usr/sbin/iptables-legacy
  - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
